### ISSUE TITLE
Popup context menus not working on Windows

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#103]
Is there a way to open the Edit Object dialogs for objects that are not in focus? (e.g., if I want to edit the sibs of the Active Person.)

Or is it necessary to switch focus to the object, then click the Toolbar's Edit icon or use the menu Edit -> Edit... (or its Ctrl-Enter keybinding)?

**Comment by cdhorn** [comment]
Right click on any frame, edit is always the first option. Or I misunderstand?

**Comment by cdhorn** [comment]
Just pushed a fix for the ref config menu error BTW.

**Comment by emyoulation** [comment]
Maybe it is a bug then. On windows, right-click is currently doing the same as a left-click... no context menus anywhere.

Id: linked_view
Description: A brows**_e_**able object view.  (Note that the 'e' is a typo)
Version: 0.63

**Comment by cdhorn** [comment]
Yes, this is a bug. Spun up an old Windows VM, installed Gramps and the plugin, and indeed it is broken. So that is half the functionality of the view that is inaccessible on Windows I guess. I am unsure why it is not working, lots I don't know here. I will continue to dig into it to try to figure it out but may need some help from Nick or Paul if I don't get anywhere.  I do know the menu is built and the popup method called, it just doesn't render.

**Comment by emyoulation** [comment]
To avoid ambiguity, I tend to use Windoze for the OS. For Dialogs & windows, I've been using "spawn" to make less ambiguous.

BTW. I am growing very fond of the Page Copy. (What do you think of the name "cheatsheet" or "CribNote" for this?) I am trying to work out a way to leverage it to tremendously (it annoys that Trumpery has made that an unpalatable word) accelerate manual parsing of Obit Transcription note in a citation.

**Comment by cdhorn** [comment]
I think the menus are fixed with b37f1002c35ebd8f9993bb78996b25ea7c36e62d if you can check on your machine. I noticed Gramps core attached them to a widget and that seems to fix the issue on Windows.

There is one new issue that cropped up with this change that I've seen twice now where it hung a short bit and logged these on the console and then it cleared up:

(gramps:378187): Gtk-CRITICAL **: 16:42:04.305: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

The context menus work in the page and group windows not just the main view.

**Comment by cdhorn** [comment]
Cleaned up the event handling, the popups should behave better with the text links and indicator and tag icons now.

I need to look at notes and what can be added at some point. At moment you can drop text from browser on an object and I open the note editor window with it but that's about it.

Closing this now.
