### ISSUE TITLE
Config option handling needs global user defaults for user defined event/attribute fields

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/LinkedView#52]
User defined field options, when changed from defaults, are unique per tree.  The reason being maybe some trees have custom events and attributes that others do not, and if users set relationship fields those people are unique per tree.  But this will get annoying very quickly if users have to customize this for every tree if modifying many options to suite their workflow. So need some sort of user defaults middle layer for them sandwiched between the global plugin defaults and tree specific options.

**Comment by cdhorn** [comment]
Adding a thought here regarding user defined fields.

Might be useful to support a couple different default profiles and key them off an attribute so people with mixed heritage can choose a different set of fields based on something like religion. The current defaults are primarily for those of European Christian descent.

**Comment by cdhorn** [comment]
Not sure I see the analogy at the moment, but there are a few thoughts being mulled over in my head. Another is to make every text field for everything user defined, so Builtin would be another field type.  Why? Well no reason calculated fields can not be plugins either.  But how useful would such a thing be?  I'm not sure the work is worth it.  Regarding plugins, same for status indicators, that could be extended as well. But if I keep changing things I'll never be done and I've other things I want to work on as well.

**Comment by cdhorn** [comment]
Commits 049649379656679f998c9da04789efe5ef0ff842 and 0ffcbb1ea0a7a14c425a5ee08569af9add6ed667 add initial support for this. Some further refinement will likely need to be done, I have not experimented too much yet only enough to get the basics working.

The default ini for the view will only contain a few options now, one to track available templates and the other the active template and a couple others. Most of the options are now in the loaded templates.

There are three sets or layers to the options:  defaults -> active template -> active configuration

The defaults are hard coded.

On start up, the active template is read in and the defaults registered to match the hard coded ones.  Any user modifications are preserved in this process as it is today.

When a database is opened a database specific template is then loaded. Here things change, instead of rebasing the defaults against the hard coded defaults they are rebased against the active settings in the active template.

During run time any configuration changes a user may make using the configuration context menus are made to the active database specific template, _not_ the active template it was rebased against.

When using the toolbar view configuration option the configuration panels for the loaded active configuration are no longer shown. A template editing panel is available:

![Screenshot from 2022-01-10 21-26-23](https://user-images.githubusercontent.com/43528418/148870691-bf22ce3d-7901-4677-abb2-14a4e3df9c65.png)

Here the active template can be changed, and when it is the active configuration will be rebased against it. View changes will provide a view of the differences between the defaults, the selected template which need not be the active one, and the active configuration:

![Screenshot from 2022-01-10 21-33-26](https://user-images.githubusercontent.com/43528418/148871191-a90f022c-c0a7-44be-83b6-fde8e959273a.png)

You may obviously copy a template to create a new one, edit one to change the name or description, edit the template itself which will load a configuration editor dialog with all of the available panels, remove template will remove the template from tracking but not delete the underlying ini file, delete will delete the underlying ini file, and import template can be used to import a template.

**Comment by emyoulation** [comment]
When you rollout the Linked/Browse View, it's going to be a major spectacle with a lot of downloads. You'll want that to go smoothly. 

I can see the potential for a lot of hitches getting through the add-on update system. And any problem experienced during install/update is going to unfairly taint the reaction to the new view. You'll want no one to have problems installing the download nor in your workflow in pushing out an emergency patch.

What do you think about releasing a single feature 5.1 Gramplet as a test balloon? (It might be a feature carved out of the Linked/Browse view.) Then, since the view will have been released that includes the feature, you could deprecate the add-on for the 5.2 cycle.

A simple Gramplet might be a bare breadcrumb list of Place objects for a Person's (or better, the Families of a Person) timeline. It could support drag'n'drop too. Adding a switch ( https://docs.gtk.org/gtk4/class.Switch.html) that syncs or uncouples the sync to the Active Person would make it less of a resource hog.

-Brian 
 
  On Sun, Jan 23, 2022 at 22:18, Christopher ***@***.***> wrote:   


Closed #52.

**Comment by emyoulation** [comment]
When you rollout the Linked/Browse View, it's going to be a major spectacle with a lot of downloads. You'll want that to go smoothly. 

I can see the potential for a lot of hitches getting through the add-on update system. And any problem experienced during install/update is going to unfairly taint the reaction to the new view. You'll want no one to have problems installing the download nor in your workflow in pushing out an emergency patch.

What do you think about releasing a single feature 5.1 Gramplet as a test balloon? (It might be a feature carved out of the Linked/Browse view.) Then, since the view will have been released that includes the feature, you could deprecate the add-on for the 5.2 cycle.

A simple Gramplet might be a bare breadcrumb list of Place objects for a Person's (or better, the Families of a Person) timeline. It could support drag'n'drop too. [Adding a switch](https://docs.gtk.org/gtk4/class.Switch.html) that syncs or uncouples the sync to the Active Person would make it less of a resource hog.
