### ISSUE TITLE
Need to develop a reasonable default color scheme for the event category, relationship and confidence options

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/LinkedView#8]
Need to develop a reasonable default color scheme for the event category, relationship and confidence options. Not being a graphic artist help would be welcome with this.

**Comment by emyoulation** [comment]
Your point about not being a graphic artist struck home with me. I'm closer to autistic than to artistic.

So I visited some sites discussing UX color selection. The structured approach with color wheel analysis and pallette categorization was intriguing.

https://uxplanet.org/best-three-color-scheme-for-music-player-5da996d7f460 introduced the Adobe color CC & various 3-color schema on color wheels.

I wanted to experiment with colors - but found the color picker and swatch organization to be inhibiting creativity. 

Conceptually, I wanted to paint context spectrums. But the pallette of Context has fixed  positioning. (i.e., the organization of swatches is fixed. In some cases, contrasting elements are adjacent. In others, they are greatly separated.) And it is necessary to pick colors (painfully) one-by-one.

It is simply too much work to create & sort a spectrum of context. One cannot "see the forest for trees" in the selector because neither the color NOR the context is sorted. 

Then I noted that you are experimenting with drag'n'drop and a thought occurred to me. What if you created a drag'n'drop color selection feature but, instead of dragging colors from a pallette to labeled swatches, you could drag the labels to a loaded & aesthetically organized pallette?

Allow the user to Load from the many artist's collections of color pallettes.  Display the pallette and drop the labels beside a color. Since the Pallettes SEEM to have a common organization structure, allow a Pallette  load to overwrite the current one. Essentially, overlaying new color themes.

Tools for reading color collections:
https://github.com/topics/adobe-swatch-exchange

https://stackoverflow.com/questions/48873754/how-to-read-photoshop-act-files-with-python

Another feature might be to set spectrums. Allow labels to be dropped between labels that already have assigned color. Order them by some context and, when you like the order, generate a spectrum fading between the end colors in steps of however many labels are in-between.

I suspect this sort of color context sorter might have broad appeal for UX designers.

**Comment by emyoulation** [comment]
By the way, perhaps if you implemented such a context spectrum picker, UX designers could be invited to comment on its interface. 

As a practical experiment, they might be enticed into contributing an attractive light & dark schema for your experimental View. 

Because of the stale first impression, Gramps does not draw any professional UX/UI talent. An innovative color configuration tool could help us collect suggestions for improving the Gramps UX in general.

**Comment by cdhorn** [comment]
Implemented scheme defaults using default Gramps palletes in 926f165b33efb043a1411f9d4a5822661d4d44e6 and  d32c294fa8eb66fead64df5730c47e0f6e2ecfcd
