### ISSUE TITLE
Cannot find the configuration for the page

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#93]
I realized that I cannot tell which page I should be modifying in the configuration Layout/ Active/Groups/Timeline.  Perhaps the currently active page should be highlighted in some way on the left page navigation sidebar? 

Pre-selecting isn't a good option because you let us change the page while the "Configure Relationships - Linked -Gramps" is open. And once you navigate to a different page in that configuration tab, you have discarded that guidepost. 

You already use dimming, boldface, borders, and a blue right edge for indicating the page selection in the page navigator. 

Pages are not labeled. So the labels in the Configuration are not so helpful.

Perhaps it could use the "Highlight focal object" border and background from the Global options for the active page?

**Comment by cdhorn** [comment]
This might be a misunderstanding of how the options work in general. The Layout tab is actually the only one with an entry per page.

The Active and Group tabs contain options related to how object frames are rendered when in the header or in a grouping so there is not a 1:1 mapping to pages. These are separate things as some options only apply to objects in the header and others to objects in a group. ie. when multiple groups are present there is less horizontal space, so an "extra" set of user customizable fields are available for a Person or Family when they are in the header. 

The Timelines tab is an exception, they are a group as well of course but treated in a special manner due to the number of options and because the data presented in them is manipulated as you can filter and include relation events. That is also why I added a base Event group to present the events as they are in Gramps separate of the Timeline group as some people might prefer one over the other.

The Global options might get sub-tabbed at some point.

Realize this approach is simplified from my first iteration at managing options, where when you launched the configuration dialog it was actually unique for each object page.  With that approach there would probably be close to 20,000 options now which is silly. If you wanted to change how a group displayed across all the pages you would be editing it for every page, or I would need to provide some kind of mass edit ability which would be a hassle.

An argument could be made that I shouldn't make it so configurable, there are currently over 1000 options.  Most developers probably wouldn't give users the number of choices I have but I think there is some value in doing so although I suspect most users will probably not change many of the defaults.

**Comment by cdhorn** [comment]
I am going to close this now that the config menu is functional.

The view configuration will continue to load the full set of options like it does today.  Note I refactored the global options and broke them out into a few different tabs now.

For the config context menu the middle mouse button click will activate it and based on the selected frame there is a menu option to load the page to edit the settings for that object (ex. Configure child group, Configure person timeline, etc) as well as an option to load the layout editor for that page as well (ex. Configure person page layout, Configure child reference page layout, etc) and some other things like enable/disable for the media bar option. 

Hideable is removed from the layout editor as no longer needed.  When collapsing a group it folds up and hides as much as possible now leaving just the little arrow marker to indicate something is there. If you decide you don't even want that left then hold down the control key and right click and that will hide away as well. Control and left click a frame by the way will open a window with a json dump of the Gramps objects that form the frame context.

**Comment by emyoulation** [comment]
Easter Egg!  Must remember to include the double-collapse in the the docs!
