### ISSUE TITLE
2ndry Object navigation 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#98]
A recent change to limit spawning of windows is changing the focus of the primary LinkView instead of its spawn.

Clicking 2ndry icons is changing the focus of the main window. Unclear if inappropriately refocusing is always, or just when the spawn limit is reached.

(I am unclear what designed behavior is intended. When the max. is reached, what happens with the next 2ndry object is clicked? Does ignore the click? Is the topmost spawned window refocused or the eldest? Maybe it refocuses a spawned window for the same object type? Behavior is only unambiguous if there is a sole spawn limit. But what happens if the user tries to reduce the limit when there are already spawn? Does it dismiss spawn? It seems like the minimum should be the greater of 1 & the current spawn count.)

**Comment by cdhorn** [comment]
Closing this as this is expected behaviour. Links clicked in spawned group or page windows trigger navigation events in the primary view.

You might ask can the spawned windows not have their own navigation. The current design doesn't allow for it and I don't think it's really needed.

Note now when you try to open more than the max allowed group or page windows you will get a warning. And the max for both can be adjusted in the global options under the display tab. If you reduce it and have windows open they will stay open. If you reduce it to one then the first window opened will be the one targetted for redraws.
