### ISSUE TITLE
Responsiveness of the live configuration changes

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#99]
The view appears to attempt to be fully interactive for every change to the Configuration change. But this overaggressive screen refresh causes the Configuration interface to be unresponsive.

Try quickly changing the Selection State of a series of 5 checkboxes in the Configuration dialog. Or clicking a numeric counter field's up/down incrementing arrow 5 times quickly.

It appears that the View attempts to complete its refresh before the GUI control is updated. And, for the series of 5 clicks, it does not refresh until 5 refreshes have been performed. 

This leads to frustration over-toggling of controls in the interface.

Request that the controls be updated before the View. And a 1/2 second delay before attempting to refresh the view to allow another control to be changed without delays. (Delay should not be cumlative. Or a busy wait.)

**Comment by cdhorn** [comment]
I don't think that's possible because of the design.

I would ideally keep it as is and defer the redraw a few seconds in case a few changes are made in rapid succession, but I seem to recall not all the standard libraries are packaged with the Windows version so am not sure if I can make use of the threading module or not. As I've not seen it used anywhere else in the code base I'm assuming not, and there may be another way to handle it but if so I don't know how.

So most likely I will change the approach and not use the signal interface and add a redraw button or something.

I need to review all the config stuff soon and will do something about this then.

**Comment by cdhorn** [comment]
Learned about Gtk timers. Commit 385e5969ceba073d0d89dfe9393c6e808e954c28 now addresses this with a 5 second redraw deferral  that resets each time an option is changed.  So going to close this one.

**Comment by emyoulation** [comment]
Wow!  So much more responsive!
Fantastic work!
